# Generated by Django 4.0.3 on 2022-08-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='id',
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
